title: jlou2u.github.io
email: justin.lewis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  jlou2u.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jlou2u.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: justinmlewis
github_username:  jlou2u

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  books:
    output: true
    permalink: /:collection/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
